name: Deploy Experimentos (Dev)

on:
  push:
    branches: [ experimentos ]
  workflow_dispatch:

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Build do projeto (Experimentos)
        run: npm run build
      
      - name: Deploy via FTP para Hostinger (Ambiente DEV)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 82.29.199.81
          username: u930134944
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./dist/
          server-dir: /public_html/global-supplements-dev/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
