name: Deploy para Hostinger

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC (21:00 horário de Brasília)
    - cron: '30 1 * * *'  # 01:30 UTC (22:30 horário de Brasília)
    - cron: '0 3 * * *'   # 03:00 UTC (00:00 horário de Brasília)
    - cron: '30 4 * * *'  # 04:30 UTC (01:30 horário de Brasília)
    - cron: '0 6 * * *'   # 06:00 UTC (03:00 horário de Brasília)
    - cron: '30 7 * * *'  # 07:30 UTC (04:30 horário de Brasília)
    - cron: '0 9 * * *'   # 09:00 UTC (06:00 horário de Brasília)
    - cron: '30 10 * * *' # 10:30 UTC (07:30 horário de Brasília)
    - cron: '0 12 * * *'  # 12:00 UTC (09:00 horário de Brasília)
    - cron: '30 13 * * *' # 13:30 UTC (10:30 horário de Brasília)
    - cron: '0 15 * * *'  # 15:00 UTC (12:00 horário de Brasília)
    - cron: '30 16 * * *' # 16:30 UTC (13:30 horário de Brasília)
    - cron: '0 18 * * *'  # 18:00 UTC (15:00 horário de Brasília)
    - cron: '30 19 * * *' # 19:30 UTC (16:30 horário de Brasília)
    - cron: '0 21 * * *'  # 21:00 UTC (18:00 horário de Brasília)
    - cron: '30 22 * * *' # 22:30 UTC (19:30 horário de Brasília)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Build do projeto
        run: npm run build
      
      - name: Deploy via FTP para Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 82.29.199.81
          username: u930134944
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./dist/
          server-dir: /public_html/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
